import { CartServiceSqlDb } from "./sql/cart";
import { ICartService } from "./contracts/cart-service";
import { IOrderService } from "./contracts/order-service";
import { IProductService } from "./contracts/product-service";
import { OrderServiceSqlDb } from "./sql/order";
import { ProductServiceSqlDb } from "./sql/product";
import { ProductServiceNoSqlDb } from "./nosql/product";
import { OrderServiceNoSqlDb } from "./nosql/order";
import { CartServiceNoSqlDb } from "./nosql/cart";
import { IAuthService } from "./contracts/auth-service";
import { AuthService } from "./nosql/auth";
import { IEncryptionService } from "./contracts/encryption-service";
import { EncryptionService } from "./utils/encryption";
import { IEmailService } from "./contracts/email/email-service";
import { EmailService } from "./email/email";
import { IEmailFactory } from "./contracts/email/email-factory";
import { EmailFactory } from "./email/email-factory";
import { IUserService } from "./contracts/user-service";
import { UserService } from "./nosql/user";

export const cartService: ICartService = new CartServiceNoSqlDb();
export const orderService: IOrderService = new OrderServiceNoSqlDb();
export const productService: IProductService = new ProductServiceNoSqlDb();
export const authService: IAuthService = new AuthService();
export const encryptionService: IEncryptionService = new EncryptionService();
export const emailService: IEmailService = new EmailService();
export const emailFactory: IEmailFactory = new EmailFactory();
export const userService: IUserService = new UserService();