import { CartServiceSqlDb } from "./sql/cart";
import { ICartService } from "./contracts/cart-service";
import { IOrderService } from "./contracts/order-service";
import { IProductService } from "./contracts/product-service";
import { OrderServiceSqlDb } from "./sql/order";
import { ProductServiceSqlDb } from "./sql/product";
import { ProductServiceNoSqlDb } from "./nosql/product";
import { OrderServiceNoSqlDb } from "./nosql/order";
import { CartServiceNoSqlDb } from "./nosql/cart";
import { IAuthService } from "./contracts/auth-service";
import { AuthService } from "./nosql/auth";
import { IEncryptionService } from "./contracts/encryption-service";
import { EncryptionService } from "./utils/encryption";
import { IEmailService } from "./contracts/email/email-service";
import { EmailService } from "./email/email";
import { IEmailFactory } from "./contracts/email/email-factory";
import { EmailFactory } from "./email/email-factory";
import { IUserService } from "./contracts/user-service";
import { UserService } from "./nosql/user";
import { IOrderItemMapper } from "./contracts/mappers/order-item-mapper";
import { OrderItemMapper } from "./mappers/order-item-mapper";
import { IOrderMapper } from "./contracts/mappers/order-mapper";
import { OrderMapper } from "./mappers/order-mapper";
import { ICartMapper } from "./contracts/mappers/cart-mapper";
import { CartMapper } from "./mappers/cart-mapper";
import { ICartItemMapper } from "./contracts/mappers/cart-item-mapper";
import { CartItemMapper } from "./mappers/cart-item-mapper";
import { IUserMapper } from "./contracts/mappers/user-mapper";
import { UserMapper } from "./mappers/user-mapper";
import { IProductMapper } from "./contracts/mappers/product-mapper";
import { ProductMapper } from "./mappers/product-mapper";
import { IAuthMapper } from "./contracts/mappers/auth-mapper";
import { AuthMapper } from "./mappers/auth-mapper";
import { IAuthValidator } from "./contracts/validators/auth";
import { AuthValidator } from "./validators/auth";
import { IProductValidator } from "./contracts/validators/product";
import { ProductValidator } from "./validators/product";
import { IInvoiceService } from "./contracts/invoice-service";
import { InvoiceService } from "./invoice";

export const cartService: ICartService = new CartServiceNoSqlDb();
export const orderService: IOrderService = new OrderServiceNoSqlDb();
export const productService: IProductService = new ProductServiceNoSqlDb();
export const authService: IAuthService = new AuthService();
export const encryptionService: IEncryptionService = new EncryptionService();
export const emailService: IEmailService = new EmailService();
export const emailFactory: IEmailFactory = new EmailFactory();
export const userService: IUserService = new UserService();
export const invoiceService: IInvoiceService = new InvoiceService();

export const orderItemMapper: IOrderItemMapper = new OrderItemMapper();
export const orderMapper: IOrderMapper = new OrderMapper();
export const cartMapper: ICartMapper = new CartMapper();
export const cartItemMapper: ICartItemMapper = new CartItemMapper();
export const userMapper: IUserMapper = new UserMapper();
export const productMapper: IProductMapper = new ProductMapper();
export const authMapper: IAuthMapper = new AuthMapper();

export const authValidator: IAuthValidator = new AuthValidator();
export const productValidator: IProductValidator = new ProductValidator();